#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += timer.o reset.o cpuinfo.o ast-scu.o ast-ahbc.o ast-sdmc.o
obj-$(CONFIG_AST_SPI_NOR) += flash.o
obj-$(CONFIG_TARGET_AST_G5) += platform_g5.o
obj-$(CONFIG_TARGET_AST_G4) += platform_g4.o
